x-backend-app: &backend-app
  build:
    context: backend
    dockerfile: Dockerfile
  restart: unless-stopped
  volumes:
    - ./backend/app:/app
    - ./backend/migration:/migration
    - ./cookies:/cookies:rw
    - local_storage:/storage
  env_file:
    - .env
  environment:
    - DATABASE__HOST=db

x-frontend-app: &frontend-app
  build:
    context: frontend
    dockerfile: Dockerfile
  env_file:
    - .env
  volumes:
    - ./frontend:/app


services:
  frontend:
    <<: *frontend-app
    command: npm run dev -- --port 3000 --host
    restart: unless-stopped
    ports:
      - "3000:3000"

  backend:
    <<: *backend-app
    command: python -m uvicorn app.web:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db

  # scheduler:
  #   <<: *backend-app
  #   command: python -m app.scheduler

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE__USER}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
      - POSTGRES_DB=${DATABASE__DB}
      - POSTGRES_PORT=${DATABASE__PORT}
    expose:
      - "${DATABASE__PORT}"
    volumes:
      - ./db:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__PASSWORD:-admin}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq


volumes:
  local_storage:


  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN__EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN__PASSWORD}
  #   configs:
  #     - source: pgadmin_servers
  #       target: /pgadmin4/servers.json

configs:
  pgadmin_servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "PostgreSQL",
            "Group": "Servers",
            "Host": "db",
            "Port": ${DATABASE__PORT},
            "MaintenanceDB": "${DATABASE__DB}",
            "Username": "${DATABASE__USER}",
            "Password": "${DATABASE__PASSWORD}",
            "SavePassword": true,
            "SSLMode": "prefer",
            "ConnectNow": true
          }
        }
      }