.PHONY: frontend-api-client-build build up down migration-autogenerate migration-upgrade clear
.PHONY: k8s-dev-kind-create k8s-dev-kind-delete k8s-dev-build k8s-dev-load k8s-dev-secrets k8s-dev-tf-apply k8s-dev-tf-destroy k8s-dev-health k8s-dev-up k8s-dev-down
.PHONY: k8s-prod-secrets k8s-prod-build k8s-prod-push k8s-prod-tf-apply k8s-prod-deploy k8s-prod-destroy

-include deploy/.env

KIND_CLUSTER ?= animestars-dev
KIND_CONFIG ?= deploy/kind/kind-config.yaml

K8S_IMAGE_TAG ?= dev
K8S_EXTRA_TAGS ?= prod,latest
K8S_INGRESS_ADDR ?= http://127.0.0.1
K8S_REGISTRY_LOCAL_PORT ?= 5000
K8S_REGISTRY_REMOTE_PORT ?= 5000

DEV_KUBECONFIG ?= $(HOME)/.kube/config
DEV_CONTEXT ?= kind-animestars-dev
DEV_NAMESPACE ?= animestars-dev
DEV_HOST_HEADER ?= animestars.local

PROD_KUBECONFIG ?= $(HOME)/.kube/config
PROD_CONTEXT ?= k3s
PROD_NAMESPACE ?= animestars-prod
PROD_SSH_TARGET ?=

frontend-api-client-build:
	cd frontend && npm run generate-api-client && cd ..

frontend-api-client-build-local:
	cd frontend && npm run generate-api-client-local && cd ..

build:
	docker compose build

build-prod:
	docker compose -f docker-compose.prod.yaml build

up:
	docker compose up -d

up-prod:
	docker compose -f docker-compose.prod.yaml up -d

down:
	docker compose down --remove-orphans

down-prod:
	docker compose -f docker-compose.prod.yaml down --remove-orphans

logs:
	docker compose logs -f backend frontend

logs-prod:
	docker compose -f docker-compose.prod.yaml logs -f backend frontend scheduler

migration-autogenerate:
	docker compose run --rm --remove-orphans backend python -m alembic revision --autogenerate

migration-upgrade:
	docker compose run --rm backend python -m alembic upgrade head

migration-upgrade-prod:
	docker compose -f docker-compose.prod.yaml run --rm backend python -m alembic upgrade head

migration-down:
	docker compose run --rm backend python -m alembic downgrade -1

backup:
	docker compose exec -T db pg_dump -U $${DATABASE__USER:-postgres} $${DATABASE__DB:-animestars} > backup_$$(date +%Y%m%d_%H%M%S).sql

restore:
	docker compose exec -T db psql -U $${DATABASE__USER:-postgres} $${DATABASE__DB:-animestars} < ${file}


clear:
	find . -name "*.pyc" -delete
	find . -name "__pycache__" -delete

black:
	docker compose run backend black .


reindex-cards:
	docker compose -f docker-compose.prod.yaml run backend python -m app.cli.reindex_cards


# ---------------- Kubernetes (Kind dev) ----------------
k8s-dev-kind-create:
	@set -euo pipefail; \
	if ! command -v kind >/dev/null 2>&1; then echo "kind is required." >&2; exit 1; fi; \
	if kind get clusters | grep -q "^$(KIND_CLUSTER)$$"; then echo "Kind cluster already exists: $(KIND_CLUSTER)"; exit 0; fi; \
	kind create cluster --name "$(KIND_CLUSTER)" --config "$(KIND_CONFIG)"; \
	kubectl cluster-info --context "kind-$(KIND_CLUSTER)" || true

k8s-dev-kind-delete:
	@set -euo pipefail; \
	if command -v kind >/dev/null 2>&1; then kind delete cluster --name "$(KIND_CLUSTER)" || true; fi

k8s-dev-build:
	@set -euo pipefail; \
	DOCKER_BUILDKIT=1 docker build -f backend/Dockerfile -t "animestars/backend:$(K8S_IMAGE_TAG)" backend; \
	DOCKER_BUILDKIT=1 docker build -f frontend/Dockerfile.prod --build-arg VITE_API_URL="" -t "animestars/frontend:$(K8S_IMAGE_TAG)" frontend

k8s-dev-load:
	@set -euo pipefail; \
	if ! command -v kind >/dev/null 2>&1; then echo "kind is required." >&2; exit 1; fi; \
	kind load docker-image --name "$(KIND_CLUSTER)" "animestars/backend:$(K8S_IMAGE_TAG)"; \
	kind load docker-image --name "$(KIND_CLUSTER)" "animestars/frontend:$(K8S_IMAGE_TAG)"

k8s-dev-secrets:
	@set -euo pipefail; \
	TFVARS="deploy/terraform/dev/terraform.auto.tfvars"; \
	if [[ -f "$${TFVARS}" ]]; then echo "Exists: $${TFVARS}"; exit 0; fi; \
	if ! command -v openssl >/dev/null 2>&1; then echo "openssl is required." >&2; exit 1; fi; \
	PASS="$$(openssl rand -base64 24 | tr -d '\n')"; \
	printf '%s\n' "# Generated by Makefile" "postgres_password = \"$${PASS}\"" > "$${TFVARS}"; \
	echo "Generated $${TFVARS}"

k8s-dev-tf-apply: k8s-dev-secrets
	@set -euo pipefail; \
	terraform -chdir=deploy/terraform/dev init -input=false; \
	terraform -chdir=deploy/terraform/dev apply \
		-var "kubeconfig_path=$(DEV_KUBECONFIG)" \
		-var "kube_context=$(DEV_CONTEXT)" \
		-var "namespace=$(DEV_NAMESPACE)" \
		-var "backend_tag=$(K8S_IMAGE_TAG)" \
		-var "frontend_tag=$(K8S_IMAGE_TAG)" \
		-auto-approve

k8s-dev-tf-destroy:
	@set -euo pipefail; \
	terraform -chdir=deploy/terraform/dev init -input=false; \
	terraform -chdir=deploy/terraform/dev destroy \
		-var "kubeconfig_path=$(DEV_KUBECONFIG)" \
		-var "kube_context=$(DEV_CONTEXT)" \
		-var "namespace=$(DEV_NAMESPACE)" \
		-auto-approve

k8s-dev-health:
	@set -euo pipefail; \
	kubectl -n "$(DEV_NAMESPACE)" rollout status deploy/backend --timeout=180s; \
	kubectl -n "$(DEV_NAMESPACE)" rollout status deploy/frontend --timeout=180s; \
	kubectl -n "$(DEV_NAMESPACE)" rollout status deploy/scheduler --timeout=180s; \
	kubectl -n "$(DEV_NAMESPACE)" rollout status statefulset/postgres --timeout=180s; \
	curl -sf -H "Host: $(DEV_HOST_HEADER)" "$(K8S_INGRESS_ADDR)/health" >/dev/null; \
	curl -sf -H "Host: $(DEV_HOST_HEADER)" "$(K8S_INGRESS_ADDR)/" >/dev/null

k8s-dev-up:
	@$(MAKE) k8s-dev-kind-create
	@$(MAKE) k8s-dev-build
	@$(MAKE) k8s-dev-load
	@$(MAKE) k8s-dev-tf-apply
	@$(MAKE) k8s-dev-health

k8s-dev-down:
	@$(MAKE) k8s-dev-tf-destroy
	@$(MAKE) k8s-dev-kind-delete


# ---------------- Kubernetes (k3s prod) ----------------
k8s-prod-secrets:
	@set -euo pipefail; \
	TFVARS="deploy/terraform/prod/terraform.auto.tfvars"; \
	if [[ -f "$${TFVARS}" ]]; then echo "Exists: $${TFVARS}"; exit 0; fi; \
	if ! command -v openssl >/dev/null 2>&1; then echo "openssl is required." >&2; exit 1; fi; \
	PASS="$$(openssl rand -base64 24 | tr -d '\n')"; \
	printf '%s\n' "# Generated by Makefile" "postgres_password = \"$${PASS}\"" > "$${TFVARS}"; \
	echo "Generated $${TFVARS}"

k8s-prod-build:
	@set -euo pipefail; \
	if [[ -z "$(K8S_IMAGE_TAG)" ]]; then echo "K8S_IMAGE_TAG is required." >&2; exit 1; fi; \
	DOCKER_BUILDKIT=1 docker build -f backend/Dockerfile -t "animestars/backend:$(K8S_IMAGE_TAG)" backend; \
	DOCKER_BUILDKIT=1 docker build -f frontend/Dockerfile.prod --build-arg VITE_API_URL="" -t "animestars/frontend:$(K8S_IMAGE_TAG)" frontend

k8s-prod-push:
	@set -euo pipefail; \
	K8S_IMAGE_TAG="$(K8S_IMAGE_TAG)" K8S_EXTRA_TAGS="$(K8S_EXTRA_TAGS)" PROD_SSH_TARGET="$(PROD_SSH_TARGET)" \
	K8S_REGISTRY_LOCAL_PORT="$(K8S_REGISTRY_LOCAL_PORT)" K8S_REGISTRY_REMOTE_PORT="$(K8S_REGISTRY_REMOTE_PORT)" \
	bash deploy/scripts/push_images_via_tunnel.sh animestars/backend animestars/frontend

k8s-prod-tf-apply: k8s-prod-secrets
	@set -euo pipefail; \
	terraform -chdir=deploy/terraform/prod init -input=false; \
	terraform -chdir=deploy/terraform/prod apply \
		-var "kubeconfig_path=$(PROD_KUBECONFIG)" \
		-var "kube_context=$(PROD_CONTEXT)" \
		-var "namespace=$(PROD_NAMESPACE)" \
		-var "backend_tag=$(K8S_IMAGE_TAG)" \
		-var "frontend_tag=$(K8S_IMAGE_TAG)" \
		-auto-approve

k8s-prod-deploy:
	@set -euo pipefail; \
	if [[ -z "$(K8S_IMAGE_TAG)" ]]; then echo "K8S_IMAGE_TAG is required (e.g. git sha)." >&2; exit 1; fi; \
	$(MAKE) k8s-prod-secrets; \
	$(MAKE) k8s-prod-build; \
	$(MAKE) k8s-prod-push; \
	$(MAKE) k8s-prod-tf-apply

k8s-prod-destroy:
	@set -euo pipefail; \
	terraform -chdir=deploy/terraform/prod init -input=false; \
	terraform -chdir=deploy/terraform/prod destroy \
		-var "kubeconfig_path=$(PROD_KUBECONFIG)" \
		-var "kube_context=$(PROD_CONTEXT)" \
		-var "namespace=$(PROD_NAMESPACE)" \
		-auto-approve
