/* tslint:disable */
/* eslint-disable */
/**
 * Anime Stars
 * Unofficial Anime Stars API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ArrayEntryFilterCardSchema
 */
export interface ArrayEntryFilterCardSchema {
    /**
     * 
     * @type {IntegerEntryFilter}
     * @memberof ArrayEntryFilterCardSchema
     */
    'length'?: IntegerEntryFilter | null;
    /**
     * 
     * @type {CardSchema}
     * @memberof ArrayEntryFilterCardSchema
     */
    'any'?: CardSchema | null;
    /**
     * 
     * @type {CardSchema}
     * @memberof ArrayEntryFilterCardSchema
     */
    'all'?: CardSchema | null;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const CardCollection = {
    Trade: 'trade',
    Need: 'need',
    Owned: 'owned',
    UnlockedOwned: 'unlocked_owned'
} as const;

export type CardCollection = typeof CardCollection[keyof typeof CardCollection];


/**
 * Filter schema for Card model
 * @export
 * @interface CardFilter
 */
export interface CardFilter {
    /**
     * 
     * @type {Array<CardFilter>}
     * @memberof CardFilter
     */
    'and'?: Array<CardFilter> | null;
    /**
     * 
     * @type {Array<CardFilter>}
     * @memberof CardFilter
     */
    'or'?: Array<CardFilter> | null;
    /**
     * 
     * @type {CardFilter}
     * @memberof CardFilter
     */
    'not'?: CardFilter | null;
    /**
     * 
     * @type {UUIDEntryFilter}
     * @memberof CardFilter
     */
    'id'?: UUIDEntryFilter | null;
    /**
     * 
     * @type {IntegerEntryFilter}
     * @memberof CardFilter
     */
    'card_id'?: IntegerEntryFilter | null;
    /**
     * 
     * @type {StringEntryFilter}
     * @memberof CardFilter
     */
    'name'?: StringEntryFilter | null;
    /**
     * 
     * @type {EnumEntryFilterCardType}
     * @memberof CardFilter
     */
    'rank'?: EnumEntryFilterCardType | null;
    /**
     * 
     * @type {StringEntryFilter}
     * @memberof CardFilter
     */
    'anime_name'?: StringEntryFilter | null;
    /**
     * 
     * @type {StringEntryFilter}
     * @memberof CardFilter
     */
    'anime_link'?: StringEntryFilter | null;
    /**
     * 
     * @type {StringEntryFilter}
     * @memberof CardFilter
     */
    'author'?: StringEntryFilter | null;
    /**
     * 
     * @type {StringEntryFilter}
     * @memberof CardFilter
     */
    'image'?: StringEntryFilter | null;
    /**
     * 
     * @type {StringEntryFilter}
     * @memberof CardFilter
     */
    'mp4'?: StringEntryFilter | null;
    /**
     * 
     * @type {StringEntryFilter}
     * @memberof CardFilter
     */
    'webm'?: StringEntryFilter | null;
    /**
     * 
     * @type {DateTimeEntryFilter}
     * @memberof CardFilter
     */
    'created_at'?: DateTimeEntryFilter | null;
    /**
     * 
     * @type {DateTimeEntryFilter}
     * @memberof CardFilter
     */
    'updated_at'?: DateTimeEntryFilter | null;
}
/**
 * 
 * @export
 * @interface CardId
 */
export interface CardId {
}
/**
 * 
 * @export
 * @interface CardPaginationResponse
 */
export interface CardPaginationResponse {
    /**
     * 
     * @type {number}
     * @memberof CardPaginationResponse
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof CardPaginationResponse
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof CardPaginationResponse
     */
    'per_page': number;
    /**
     * 
     * @type {Array<CardSchema>}
     * @memberof CardPaginationResponse
     */
    'items': Array<CardSchema>;
    /**
     * 
     * @type {number}
     * @memberof CardPaginationResponse
     */
    'total_pages': number;
    /**
     * 
     * @type {boolean}
     * @memberof CardPaginationResponse
     */
    'has_next': boolean;
}
/**
 * 
 * @export
 * @interface CardQuery
 */
export interface CardQuery {
    /**
     * 
     * @type {CardFilter}
     * @memberof CardQuery
     */
    'filter'?: CardFilter | null;
    /**
     * 
     * @type {OrderBy}
     * @memberof CardQuery
     */
    'order_by'?: OrderBy | null;
    /**
     * 
     * @type {number}
     * @memberof CardQuery
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof CardQuery
     */
    'per_page'?: number;
}
/**
 * 
 * @export
 * @interface CardSchema
 */
export interface CardSchema {
    /**
     * 
     * @type {string}
     * @memberof CardSchema
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof CardSchema
     */
    'card_id': number;
    /**
     * 
     * @type {string}
     * @memberof CardSchema
     */
    'name': string;
    /**
     * 
     * @type {CardType}
     * @memberof CardSchema
     */
    'rank': CardType;
    /**
     * 
     * @type {string}
     * @memberof CardSchema
     */
    'anime_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardSchema
     */
    'anime_link'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardSchema
     */
    'author'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardSchema
     */
    'image'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardSchema
     */
    'mp4'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardSchema
     */
    'webm'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardSchema
     */
    'created_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardSchema
     */
    'updated_at'?: string | null;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const CardType = {
    Ass: 'ass',
    S: 's',
    A: 'a',
    B: 'b',
    C: 'c',
    D: 'd',
    E: 'e'
} as const;

export type CardType = typeof CardType[keyof typeof CardType];


/**
 * Filter schema for CardUsersStats model
 * @export
 * @interface CardUsersStatsFilter
 */
export interface CardUsersStatsFilter {
    /**
     * 
     * @type {Array<CardUsersStatsFilter>}
     * @memberof CardUsersStatsFilter
     */
    'and'?: Array<CardUsersStatsFilter> | null;
    /**
     * 
     * @type {Array<CardUsersStatsFilter>}
     * @memberof CardUsersStatsFilter
     */
    'or'?: Array<CardUsersStatsFilter> | null;
    /**
     * 
     * @type {CardUsersStatsFilter}
     * @memberof CardUsersStatsFilter
     */
    'not'?: CardUsersStatsFilter | null;
    /**
     * 
     * @type {UUIDEntryFilter}
     * @memberof CardUsersStatsFilter
     */
    'id'?: UUIDEntryFilter | null;
    /**
     * 
     * @type {IntegerEntryFilter}
     * @memberof CardUsersStatsFilter
     */
    'card_id'?: IntegerEntryFilter | null;
    /**
     * 
     * @type {EnumEntryFilterCardCollection}
     * @memberof CardUsersStatsFilter
     */
    'collection'?: EnumEntryFilterCardCollection | null;
    /**
     * 
     * @type {IntegerEntryFilter}
     * @memberof CardUsersStatsFilter
     */
    'count'?: IntegerEntryFilter | null;
    /**
     * 
     * @type {DateTimeEntryFilter}
     * @memberof CardUsersStatsFilter
     */
    'created_at'?: DateTimeEntryFilter | null;
    /**
     * 
     * @type {DateTimeEntryFilter}
     * @memberof CardUsersStatsFilter
     */
    'updated_at'?: DateTimeEntryFilter | null;
}
/**
 * 
 * @export
 * @interface CardUsersStatsQuery
 */
export interface CardUsersStatsQuery {
    /**
     * 
     * @type {CardUsersStatsFilter}
     * @memberof CardUsersStatsQuery
     */
    'filter'?: CardUsersStatsFilter | null;
    /**
     * 
     * @type {OrderBy1}
     * @memberof CardUsersStatsQuery
     */
    'order_by'?: OrderBy1 | null;
    /**
     * 
     * @type {number}
     * @memberof CardUsersStatsQuery
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof CardUsersStatsQuery
     */
    'per_page'?: number;
}
/**
 * 
 * @export
 * @interface CardUsersStatsResponse
 */
export interface CardUsersStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof CardUsersStatsResponse
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof CardUsersStatsResponse
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof CardUsersStatsResponse
     */
    'per_page': number;
    /**
     * 
     * @type {Array<CardUsersStatsSchema>}
     * @memberof CardUsersStatsResponse
     */
    'items': Array<CardUsersStatsSchema>;
    /**
     * 
     * @type {number}
     * @memberof CardUsersStatsResponse
     */
    'total_pages': number;
    /**
     * 
     * @type {boolean}
     * @memberof CardUsersStatsResponse
     */
    'has_next': boolean;
}
/**
 * 
 * @export
 * @interface CardUsersStatsSchema
 */
export interface CardUsersStatsSchema {
    /**
     * 
     * @type {string}
     * @memberof CardUsersStatsSchema
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof CardUsersStatsSchema
     */
    'card_id': number;
    /**
     * 
     * @type {CardCollection}
     * @memberof CardUsersStatsSchema
     */
    'collection': CardCollection;
    /**
     * 
     * @type {number}
     * @memberof CardUsersStatsSchema
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof CardUsersStatsSchema
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof CardUsersStatsSchema
     */
    'updated_at': string;
}


/**
 * DateTime field filters
 * @export
 * @interface DateTimeEntryFilter
 */
export interface DateTimeEntryFilter {
    /**
     * 
     * @type {string}
     * @memberof DateTimeEntryFilter
     */
    'eq'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DateTimeEntryFilter
     */
    'ne'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DateTimeEntryFilter
     */
    'is_null'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof DateTimeEntryFilter
     */
    'gt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DateTimeEntryFilter
     */
    'gte'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DateTimeEntryFilter
     */
    'lt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DateTimeEntryFilter
     */
    'lte'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DateTimeEntryFilter
     */
    'before'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DateTimeEntryFilter
     */
    'after'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DateTimeEntryFilter
     */
    'between'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DateTimeEntryFilter
     */
    'in'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DateTimeEntryFilter
     */
    'not_in'?: Array<string> | null;
}
/**
 * Schema for detailed deck view with all cards
 * @export
 * @interface DeckDetailSchema
 */
export interface DeckDetailSchema {
    /**
     * 
     * @type {string}
     * @memberof DeckDetailSchema
     */
    'anime_link': string;
    /**
     * 
     * @type {string}
     * @memberof DeckDetailSchema
     */
    'anime_name': string | null;
    /**
     * 
     * @type {Array<CardSchema>}
     * @memberof DeckDetailSchema
     */
    'cards': Array<CardSchema>;
}
/**
 * 
 * @export
 * @interface DeckFilter
 */
export interface DeckFilter {
    /**
     * 
     * @type {ArrayEntryFilterCardSchema}
     * @memberof DeckFilter
     */
    'cards'?: ArrayEntryFilterCardSchema | null;
    /**
     * 
     * @type {StringEntryFilter}
     * @memberof DeckFilter
     */
    'anime_name'?: StringEntryFilter | null;
    /**
     * 
     * @type {StringEntryFilter}
     * @memberof DeckFilter
     */
    'anime_link'?: StringEntryFilter | null;
    /**
     * 
     * @type {IntegerEntryFilter}
     * @memberof DeckFilter
     */
    'card_count'?: IntegerEntryFilter | null;
}
/**
 * Paginated response for deck listings
 * @export
 * @interface DeckPaginationResponse
 */
export interface DeckPaginationResponse {
    /**
     * 
     * @type {number}
     * @memberof DeckPaginationResponse
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof DeckPaginationResponse
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof DeckPaginationResponse
     */
    'per_page': number;
    /**
     * 
     * @type {Array<DeckSummarySchema>}
     * @memberof DeckPaginationResponse
     */
    'items': Array<DeckSummarySchema>;
    /**
     * 
     * @type {number}
     * @memberof DeckPaginationResponse
     */
    'total_pages': number;
    /**
     * 
     * @type {boolean}
     * @memberof DeckPaginationResponse
     */
    'has_next': boolean;
}
/**
 * 
 * @export
 * @interface DeckQuery
 */
export interface DeckQuery {
    /**
     * 
     * @type {DeckFilter}
     * @memberof DeckQuery
     */
    'filter'?: DeckFilter | null;
    /**
     * 
     * @type {OrderBy2}
     * @memberof DeckQuery
     */
    'order_by'?: OrderBy2 | null;
    /**
     * 
     * @type {number}
     * @memberof DeckQuery
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof DeckQuery
     */
    'per_page'?: number;
}
/**
 * Schema for deck summary in listings
 * @export
 * @interface DeckSummarySchema
 */
export interface DeckSummarySchema {
    /**
     * 
     * @type {string}
     * @memberof DeckSummarySchema
     */
    'anime_link': string;
    /**
     * 
     * @type {string}
     * @memberof DeckSummarySchema
     */
    'anime_name': string | null;
    /**
     * 
     * @type {number}
     * @memberof DeckSummarySchema
     */
    'card_count': number;
    /**
     * 
     * @type {Array<CardSchema>}
     * @memberof DeckSummarySchema
     */
    'cards'?: Array<CardSchema>;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const Direction = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type Direction = typeof Direction[keyof typeof Direction];


/**
 * 
 * @export
 * @interface EnumEntryFilterCardCollection
 */
export interface EnumEntryFilterCardCollection {
    /**
     * 
     * @type {CardCollection}
     * @memberof EnumEntryFilterCardCollection
     */
    'eq'?: CardCollection | null;
    /**
     * 
     * @type {CardCollection}
     * @memberof EnumEntryFilterCardCollection
     */
    'ne'?: CardCollection | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnumEntryFilterCardCollection
     */
    'is_null'?: boolean | null;
    /**
     * 
     * @type {Array<CardCollection>}
     * @memberof EnumEntryFilterCardCollection
     */
    'in'?: Array<CardCollection> | null;
    /**
     * 
     * @type {Array<CardCollection>}
     * @memberof EnumEntryFilterCardCollection
     */
    'not_in'?: Array<CardCollection> | null;
}


/**
 * 
 * @export
 * @interface EnumEntryFilterCardType
 */
export interface EnumEntryFilterCardType {
    /**
     * 
     * @type {CardType}
     * @memberof EnumEntryFilterCardType
     */
    'eq'?: CardType | null;
    /**
     * 
     * @type {CardType}
     * @memberof EnumEntryFilterCardType
     */
    'ne'?: CardType | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnumEntryFilterCardType
     */
    'is_null'?: boolean | null;
    /**
     * 
     * @type {Array<CardType>}
     * @memberof EnumEntryFilterCardType
     */
    'in'?: Array<CardType> | null;
    /**
     * 
     * @type {Array<CardType>}
     * @memberof EnumEntryFilterCardType
     */
    'not_in'?: Array<CardType> | null;
}


/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     * 
     * @type {string}
     * @memberof HealthResponse
     */
    'status': string;
    /**
     * 
     * @type {number}
     * @memberof HealthResponse
     */
    'ping': number;
    /**
     * 
     * @type {string}
     * @memberof HealthResponse
     */
    'uptime_formatted': string;
    /**
     * 
     * @type {object}
     * @memberof HealthResponse
     */
    'database_stats': object;
}
/**
 * Integer field filters
 * @export
 * @interface IntegerEntryFilter
 */
export interface IntegerEntryFilter {
    /**
     * 
     * @type {number}
     * @memberof IntegerEntryFilter
     */
    'eq'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IntegerEntryFilter
     */
    'ne'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof IntegerEntryFilter
     */
    'is_null'?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof IntegerEntryFilter
     */
    'gt'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IntegerEntryFilter
     */
    'gte'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IntegerEntryFilter
     */
    'lt'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IntegerEntryFilter
     */
    'lte'?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof IntegerEntryFilter
     */
    'between'?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof IntegerEntryFilter
     */
    'in'?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof IntegerEntryFilter
     */
    'not_in'?: Array<number> | null;
}
/**
 * Order by for the pagination
 * @export
 * @interface OrderBy
 */
export interface OrderBy {
}
/**
 * Order by for the pagination
 * @export
 * @interface OrderBy1
 */
export interface OrderBy1 {
}
/**
 * Order by for the pagination
 * @export
 * @interface OrderBy2
 */
export interface OrderBy2 {
}
/**
 * 
 * @export
 * @interface Property
 */
export interface Property {
}
/**
 * 
 * @export
 * @interface SortGenericLiteralAnimeNameAscAnimeNameDescAnimeNameCardCountAscCardCountDescCardCount
 */
export interface SortGenericLiteralAnimeNameAscAnimeNameDescAnimeNameCardCountAscCardCountDescCardCount {
    /**
     * 
     * @type {string}
     * @memberof SortGenericLiteralAnimeNameAscAnimeNameDescAnimeNameCardCountAscCardCountDescCardCount
     */
    'property': SortGenericLiteralAnimeNameAscAnimeNameDescAnimeNameCardCountAscCardCountDescCardCountPropertyEnum;
    /**
     * 
     * @type {Direction}
     * @memberof SortGenericLiteralAnimeNameAscAnimeNameDescAnimeNameCardCountAscCardCountDescCardCount
     */
    'direction': Direction;
}

export const SortGenericLiteralAnimeNameAscAnimeNameDescAnimeNameCardCountAscCardCountDescCardCountPropertyEnum = {
    AnimeNameAsc: 'anime_name asc',
    AnimeNameDesc: 'anime_name desc',
    AnimeName: 'anime_name',
    CardCountAsc: 'card_count asc',
    CardCountDesc: 'card_count desc',
    CardCount: 'card_count'
} as const;

export type SortGenericLiteralAnimeNameAscAnimeNameDescAnimeNameCardCountAscCardCountDescCardCountPropertyEnum = typeof SortGenericLiteralAnimeNameAscAnimeNameDescAnimeNameCardCountAscCardCountDescCardCountPropertyEnum[keyof typeof SortGenericLiteralAnimeNameAscAnimeNameDescAnimeNameCardCountAscCardCountDescCardCountPropertyEnum];

/**
 * 
 * @export
 * @interface SortGenericLiteralIdCardIdCollectionCountCreatedAtUpdatedAt
 */
export interface SortGenericLiteralIdCardIdCollectionCountCreatedAtUpdatedAt {
    /**
     * 
     * @type {string}
     * @memberof SortGenericLiteralIdCardIdCollectionCountCreatedAtUpdatedAt
     */
    'property': SortGenericLiteralIdCardIdCollectionCountCreatedAtUpdatedAtPropertyEnum;
    /**
     * 
     * @type {Direction}
     * @memberof SortGenericLiteralIdCardIdCollectionCountCreatedAtUpdatedAt
     */
    'direction': Direction;
}

export const SortGenericLiteralIdCardIdCollectionCountCreatedAtUpdatedAtPropertyEnum = {
    Id: 'id',
    CardId: 'card_id',
    Collection: 'collection',
    Count: 'count',
    CreatedAt: 'created_at',
    UpdatedAt: 'updated_at'
} as const;

export type SortGenericLiteralIdCardIdCollectionCountCreatedAtUpdatedAtPropertyEnum = typeof SortGenericLiteralIdCardIdCollectionCountCreatedAtUpdatedAtPropertyEnum[keyof typeof SortGenericLiteralIdCardIdCollectionCountCreatedAtUpdatedAtPropertyEnum];

/**
 * 
 * @export
 * @interface SortGenericUnionLiteralIdCardIdNameRankAnimeNameAnimeLinkAuthorImageMp4WebmCreatedAtUpdatedAtStr
 */
export interface SortGenericUnionLiteralIdCardIdNameRankAnimeNameAnimeLinkAuthorImageMp4WebmCreatedAtUpdatedAtStr {
    /**
     * 
     * @type {Property}
     * @memberof SortGenericUnionLiteralIdCardIdNameRankAnimeNameAnimeLinkAuthorImageMp4WebmCreatedAtUpdatedAtStr
     */
    'property': Property;
    /**
     * 
     * @type {Direction}
     * @memberof SortGenericUnionLiteralIdCardIdNameRankAnimeNameAnimeLinkAuthorImageMp4WebmCreatedAtUpdatedAtStr
     */
    'direction': Direction;
}


/**
 * String field filters
 * @export
 * @interface StringEntryFilter
 */
export interface StringEntryFilter {
    /**
     * 
     * @type {string}
     * @memberof StringEntryFilter
     */
    'eq'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringEntryFilter
     */
    'ne'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StringEntryFilter
     */
    'is_null'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof StringEntryFilter
     */
    'contains'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringEntryFilter
     */
    'icontains'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringEntryFilter
     */
    'like'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringEntryFilter
     */
    'ilike'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringEntryFilter
     */
    'not_like'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringEntryFilter
     */
    'startswith'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringEntryFilter
     */
    'endswith'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof StringEntryFilter
     */
    'in'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof StringEntryFilter
     */
    'not_in'?: Array<string> | null;
}
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    'access_token': string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    'token_type'?: string;
}
/**
 * UUID field filters
 * @export
 * @interface UUIDEntryFilter
 */
export interface UUIDEntryFilter {
    /**
     * 
     * @type {string}
     * @memberof UUIDEntryFilter
     */
    'eq'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UUIDEntryFilter
     */
    'ne'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UUIDEntryFilter
     */
    'is_null'?: boolean | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UUIDEntryFilter
     */
    'in'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UUIDEntryFilter
     */
    'not_in'?: Array<string> | null;
}
/**
 * 
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'id': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponse
     */
    'is_active': boolean;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'created_at': string;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Login
         * @param {string} username 
         * @param {string} password 
         * @param {string | null} [grantType] 
         * @param {string} [scope] 
         * @param {string | null} [clientId] 
         * @param {string | null} [clientSecret] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginApiAuthLoginPost: async (username: string, password: string, grantType?: string | null, scope?: string, clientId?: string | null, clientSecret?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('loginApiAuthLoginPost', 'username', username)
            // verify required parameter 'password' is not null or undefined
            assertParamExists('loginApiAuthLoginPost', 'password', password)
            const localVarPath = `/api/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();


            if (grantType !== undefined) { 
                localVarFormParams.set('grant_type', grantType as any);
            }
    
            if (username !== undefined) { 
                localVarFormParams.set('username', username as any);
            }
    
            if (password !== undefined) { 
                localVarFormParams.set('password', password as any);
            }
    
            if (scope !== undefined) { 
                localVarFormParams.set('scope', scope as any);
            }
    
            if (clientId !== undefined) { 
                localVarFormParams.set('client_id', clientId as any);
            }
    
            if (clientSecret !== undefined) { 
                localVarFormParams.set('client_secret', clientSecret as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logoutApiAuthLogoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Read Users Me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readUsersMeApiAuthMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerApiAuthRegisterPost: async (userCreate: UserCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userCreate' is not null or undefined
            assertParamExists('registerApiAuthRegisterPost', 'userCreate', userCreate)
            const localVarPath = `/api/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Login
         * @param {string} username 
         * @param {string} password 
         * @param {string | null} [grantType] 
         * @param {string} [scope] 
         * @param {string | null} [clientId] 
         * @param {string | null} [clientSecret] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginApiAuthLoginPost(username: string, password: string, grantType?: string | null, scope?: string, clientId?: string | null, clientSecret?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Token>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginApiAuthLoginPost(username, password, grantType, scope, clientId, clientSecret, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.loginApiAuthLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logoutApiAuthLogoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logoutApiAuthLogoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.logoutApiAuthLogoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Read Users Me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readUsersMeApiAuthMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readUsersMeApiAuthMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.readUsersMeApiAuthMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerApiAuthRegisterPost(userCreate: UserCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerApiAuthRegisterPost(userCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.registerApiAuthRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Login
         * @param {string} username 
         * @param {string} password 
         * @param {string | null} [grantType] 
         * @param {string} [scope] 
         * @param {string | null} [clientId] 
         * @param {string | null} [clientSecret] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginApiAuthLoginPost(username: string, password: string, grantType?: string | null, scope?: string, clientId?: string | null, clientSecret?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<Token> {
            return localVarFp.loginApiAuthLoginPost(username, password, grantType, scope, clientId, clientSecret, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logoutApiAuthLogoutPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.logoutApiAuthLogoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Read Users Me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readUsersMeApiAuthMeGet(options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.readUsersMeApiAuthMeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerApiAuthRegisterPost(userCreate: UserCreate, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.registerApiAuthRegisterPost(userCreate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Login
     * @param {string} username 
     * @param {string} password 
     * @param {string | null} [grantType] 
     * @param {string} [scope] 
     * @param {string | null} [clientId] 
     * @param {string | null} [clientSecret] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public loginApiAuthLoginPost(username: string, password: string, grantType?: string | null, scope?: string, clientId?: string | null, clientSecret?: string | null, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginApiAuthLoginPost(username, password, grantType, scope, clientId, clientSecret, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public logoutApiAuthLogoutPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).logoutApiAuthLogoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Read Users Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public readUsersMeApiAuthMeGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).readUsersMeApiAuthMeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register
     * @param {UserCreate} userCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public registerApiAuthRegisterPost(userCreate: UserCreate, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).registerApiAuthRegisterPost(userCreate, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CardApi - axios parameter creator
 * @export
 */
export const CardApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Card
         * @param {CardId} cardId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCardApiCardCardIdGet: async (cardId: CardId, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cardId' is not null or undefined
            assertParamExists('getCardApiCardCardIdGet', 'cardId', cardId)
            const localVarPath = `/api/card/{card_id}`
                .replace(`{${"card_id"}}`, encodeURIComponent(String(cardId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get cards with filtering support.  The new filter system supports: - All standard fields: id, card_id, name, rank, anime_name, anime_link, author, image, mp4, webm - Computed fields: author_username (demonstrates custom logic)  Example filter usage: {     \"filter\": {         \"name\": {\"contains\": \"Naruto\"},         \"author_username\": {\"icontains\": \"user\"},         \"rank\": {\"eq\": \"S\"}     } }
         * @summary Get Cards
         * @param {CardQuery} cardQuery 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCardsApiCardPost: async (cardQuery: CardQuery, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cardQuery' is not null or undefined
            assertParamExists('getCardsApiCardPost', 'cardQuery', cardQuery)
            const localVarPath = `/api/card/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cardQuery, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CardApi - functional programming interface
 * @export
 */
export const CardApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CardApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Card
         * @param {CardId} cardId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCardApiCardCardIdGet(cardId: CardId, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CardSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCardApiCardCardIdGet(cardId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardApi.getCardApiCardCardIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get cards with filtering support.  The new filter system supports: - All standard fields: id, card_id, name, rank, anime_name, anime_link, author, image, mp4, webm - Computed fields: author_username (demonstrates custom logic)  Example filter usage: {     \"filter\": {         \"name\": {\"contains\": \"Naruto\"},         \"author_username\": {\"icontains\": \"user\"},         \"rank\": {\"eq\": \"S\"}     } }
         * @summary Get Cards
         * @param {CardQuery} cardQuery 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCardsApiCardPost(cardQuery: CardQuery, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CardPaginationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCardsApiCardPost(cardQuery, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardApi.getCardsApiCardPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CardApi - factory interface
 * @export
 */
export const CardApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CardApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Card
         * @param {CardId} cardId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCardApiCardCardIdGet(cardId: CardId, options?: RawAxiosRequestConfig): AxiosPromise<CardSchema> {
            return localVarFp.getCardApiCardCardIdGet(cardId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get cards with filtering support.  The new filter system supports: - All standard fields: id, card_id, name, rank, anime_name, anime_link, author, image, mp4, webm - Computed fields: author_username (demonstrates custom logic)  Example filter usage: {     \"filter\": {         \"name\": {\"contains\": \"Naruto\"},         \"author_username\": {\"icontains\": \"user\"},         \"rank\": {\"eq\": \"S\"}     } }
         * @summary Get Cards
         * @param {CardQuery} cardQuery 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCardsApiCardPost(cardQuery: CardQuery, options?: RawAxiosRequestConfig): AxiosPromise<CardPaginationResponse> {
            return localVarFp.getCardsApiCardPost(cardQuery, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CardApi - object-oriented interface
 * @export
 * @class CardApi
 * @extends {BaseAPI}
 */
export class CardApi extends BaseAPI {
    /**
     * 
     * @summary Get Card
     * @param {CardId} cardId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardApi
     */
    public getCardApiCardCardIdGet(cardId: CardId, options?: RawAxiosRequestConfig) {
        return CardApiFp(this.configuration).getCardApiCardCardIdGet(cardId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get cards with filtering support.  The new filter system supports: - All standard fields: id, card_id, name, rank, anime_name, anime_link, author, image, mp4, webm - Computed fields: author_username (demonstrates custom logic)  Example filter usage: {     \"filter\": {         \"name\": {\"contains\": \"Naruto\"},         \"author_username\": {\"icontains\": \"user\"},         \"rank\": {\"eq\": \"S\"}     } }
     * @summary Get Cards
     * @param {CardQuery} cardQuery 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardApi
     */
    public getCardsApiCardPost(cardQuery: CardQuery, options?: RawAxiosRequestConfig) {
        return CardApiFp(this.configuration).getCardsApiCardPost(cardQuery, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CardStatsApi - axios parameter creator
 * @export
 */
export const CardStatsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Card Users Stats By Card Id
         * @param {CardUsersStatsQuery} cardUsersStatsQuery 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCardUsersStatsByCardIdApiCardStatsPost: async (cardUsersStatsQuery: CardUsersStatsQuery, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cardUsersStatsQuery' is not null or undefined
            assertParamExists('getCardUsersStatsByCardIdApiCardStatsPost', 'cardUsersStatsQuery', cardUsersStatsQuery)
            const localVarPath = `/api/card/stats/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cardUsersStatsQuery, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Last Card Users Stats
         * @param {number} cardId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLastCardUsersStatsApiCardStatsLastGet: async (cardId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cardId' is not null or undefined
            assertParamExists('getLastCardUsersStatsApiCardStatsLastGet', 'cardId', cardId)
            const localVarPath = `/api/card/stats/last`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (cardId !== undefined) {
                localVarQueryParameter['card_id'] = cardId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Last Card Users Stats Bulk
         * @param {Array<number>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLastCardUsersStatsBulkApiCardStatsLastBulkGet: async (requestBody: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('getLastCardUsersStatsBulkApiCardStatsLastBulkGet', 'requestBody', requestBody)
            const localVarPath = `/api/card/stats/last/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CardStatsApi - functional programming interface
 * @export
 */
export const CardStatsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CardStatsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Card Users Stats By Card Id
         * @param {CardUsersStatsQuery} cardUsersStatsQuery 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCardUsersStatsByCardIdApiCardStatsPost(cardUsersStatsQuery: CardUsersStatsQuery, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CardUsersStatsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCardUsersStatsByCardIdApiCardStatsPost(cardUsersStatsQuery, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardStatsApi.getCardUsersStatsByCardIdApiCardStatsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Last Card Users Stats
         * @param {number} cardId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLastCardUsersStatsApiCardStatsLastGet(cardId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CardUsersStatsSchema>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLastCardUsersStatsApiCardStatsLastGet(cardId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardStatsApi.getLastCardUsersStatsApiCardStatsLastGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Last Card Users Stats Bulk
         * @param {Array<number>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLastCardUsersStatsBulkApiCardStatsLastBulkGet(requestBody: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CardUsersStatsSchema>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLastCardUsersStatsBulkApiCardStatsLastBulkGet(requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CardStatsApi.getLastCardUsersStatsBulkApiCardStatsLastBulkGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CardStatsApi - factory interface
 * @export
 */
export const CardStatsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CardStatsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Card Users Stats By Card Id
         * @param {CardUsersStatsQuery} cardUsersStatsQuery 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCardUsersStatsByCardIdApiCardStatsPost(cardUsersStatsQuery: CardUsersStatsQuery, options?: RawAxiosRequestConfig): AxiosPromise<CardUsersStatsResponse> {
            return localVarFp.getCardUsersStatsByCardIdApiCardStatsPost(cardUsersStatsQuery, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Last Card Users Stats
         * @param {number} cardId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLastCardUsersStatsApiCardStatsLastGet(cardId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<CardUsersStatsSchema>> {
            return localVarFp.getLastCardUsersStatsApiCardStatsLastGet(cardId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Last Card Users Stats Bulk
         * @param {Array<number>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLastCardUsersStatsBulkApiCardStatsLastBulkGet(requestBody: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<Array<CardUsersStatsSchema>> {
            return localVarFp.getLastCardUsersStatsBulkApiCardStatsLastBulkGet(requestBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CardStatsApi - object-oriented interface
 * @export
 * @class CardStatsApi
 * @extends {BaseAPI}
 */
export class CardStatsApi extends BaseAPI {
    /**
     * 
     * @summary Get Card Users Stats By Card Id
     * @param {CardUsersStatsQuery} cardUsersStatsQuery 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardStatsApi
     */
    public getCardUsersStatsByCardIdApiCardStatsPost(cardUsersStatsQuery: CardUsersStatsQuery, options?: RawAxiosRequestConfig) {
        return CardStatsApiFp(this.configuration).getCardUsersStatsByCardIdApiCardStatsPost(cardUsersStatsQuery, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Last Card Users Stats
     * @param {number} cardId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardStatsApi
     */
    public getLastCardUsersStatsApiCardStatsLastGet(cardId: number, options?: RawAxiosRequestConfig) {
        return CardStatsApiFp(this.configuration).getLastCardUsersStatsApiCardStatsLastGet(cardId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Last Card Users Stats Bulk
     * @param {Array<number>} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardStatsApi
     */
    public getLastCardUsersStatsBulkApiCardStatsLastBulkGet(requestBody: Array<number>, options?: RawAxiosRequestConfig) {
        return CardStatsApiFp(this.configuration).getLastCardUsersStatsBulkApiCardStatsLastBulkGet(requestBody, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DeckApi - axios parameter creator
 * @export
 */
export const DeckApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get detailed view of a specific deck with all its cards
         * @summary Get Deck Detail
         * @param {string} animeLink 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeckDetailApiDeckDetailGet: async (animeLink: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'animeLink' is not null or undefined
            assertParamExists('getDeckDetailApiDeckDetailGet', 'animeLink', animeLink)
            const localVarPath = `/api/deck/detail`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (animeLink !== undefined) {
                localVarQueryParameter['anime_link'] = animeLink;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all decks (anime grouped by anime_link) with pagination, search and sorting
         * @summary Get Decks
         * @param {DeckQuery} deckQuery 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDecksApiDeckPost: async (deckQuery: DeckQuery, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deckQuery' is not null or undefined
            assertParamExists('getDecksApiDeckPost', 'deckQuery', deckQuery)
            const localVarPath = `/api/deck/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deckQuery, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeckApi - functional programming interface
 * @export
 */
export const DeckApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DeckApiAxiosParamCreator(configuration)
    return {
        /**
         * Get detailed view of a specific deck with all its cards
         * @summary Get Deck Detail
         * @param {string} animeLink 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDeckDetailApiDeckDetailGet(animeLink: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeckDetailSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDeckDetailApiDeckDetailGet(animeLink, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeckApi.getDeckDetailApiDeckDetailGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all decks (anime grouped by anime_link) with pagination, search and sorting
         * @summary Get Decks
         * @param {DeckQuery} deckQuery 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDecksApiDeckPost(deckQuery: DeckQuery, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeckPaginationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDecksApiDeckPost(deckQuery, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeckApi.getDecksApiDeckPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DeckApi - factory interface
 * @export
 */
export const DeckApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DeckApiFp(configuration)
    return {
        /**
         * Get detailed view of a specific deck with all its cards
         * @summary Get Deck Detail
         * @param {string} animeLink 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeckDetailApiDeckDetailGet(animeLink: string, options?: RawAxiosRequestConfig): AxiosPromise<DeckDetailSchema> {
            return localVarFp.getDeckDetailApiDeckDetailGet(animeLink, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all decks (anime grouped by anime_link) with pagination, search and sorting
         * @summary Get Decks
         * @param {DeckQuery} deckQuery 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDecksApiDeckPost(deckQuery: DeckQuery, options?: RawAxiosRequestConfig): AxiosPromise<DeckPaginationResponse> {
            return localVarFp.getDecksApiDeckPost(deckQuery, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeckApi - object-oriented interface
 * @export
 * @class DeckApi
 * @extends {BaseAPI}
 */
export class DeckApi extends BaseAPI {
    /**
     * Get detailed view of a specific deck with all its cards
     * @summary Get Deck Detail
     * @param {string} animeLink 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeckApi
     */
    public getDeckDetailApiDeckDetailGet(animeLink: string, options?: RawAxiosRequestConfig) {
        return DeckApiFp(this.configuration).getDeckDetailApiDeckDetailGet(animeLink, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all decks (anime grouped by anime_link) with pagination, search and sorting
     * @summary Get Decks
     * @param {DeckQuery} deckQuery 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeckApi
     */
    public getDecksApiDeckPost(deckQuery: DeckQuery, options?: RawAxiosRequestConfig) {
        return DeckApiFp(this.configuration).getDecksApiDeckPost(deckQuery, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Read Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readRootGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Read Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readRootGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readRootGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.readRootGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Read Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readRootGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.readRootGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Read Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readRootGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).readRootGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HealthApi - axios parameter creator
 * @export
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * 
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse> {
            return localVarFp.healthHealthGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI {
    /**
     * 
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthHealthGet(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthHealthGet(options).then((request) => request(this.axios, this.basePath));
    }
}



