apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: db:$GRAFANA_DS_PG_PORT
    database: $GRAFANA_DS_PG_DATABASE
    user: $GRAFANA_DS_PG_USER
    secureJsonData:
      password: $GRAFANA_DS_PG_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    editable: false
