"""empty message

Revision ID: 326cf388b71c
Revises:
Create Date: 2025-04-10 20:01:36.924999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "326cf388b71c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


RANK_ENUM = sa.Enum("ASS", "S", "A", "B", "C", "D", "E", name="cardtype")
COLLECTION_ENUM = sa.Enum("TRADE", "NEED", "OWNED", name="cardcollection")
CARD_STATE_ENUM = sa.Enum("ON_TRADE", "LOCKED", "FRIENDS_ONLY", "TROPHY", name="cardstate")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animestars_users",
        sa.Column("username", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("username"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "animestars_cards",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("rank", RANK_ENUM, nullable=False),
        sa.Column("anime_name", sa.String(), nullable=True),
        sa.Column("anime_link", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("mp4", sa.String(), nullable=True),
        sa.Column("webm", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author"],
            ["animestars_users.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "animestars_card_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("user_username", sa.String(), nullable=False),
        sa.Column("collection", COLLECTION_ENUM, nullable=False),
        sa.Column("state", CARD_STATE_ENUM, nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["animestars_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_username"],
            ["animestars_users.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_animestars_card_users_card_id"),
        "animestars_card_users",
        ["card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_animestars_card_users_collection"),
        "animestars_card_users",
        ["collection"],
        unique=False,
    )
    op.create_index(
        op.f("ix_animestars_card_users_user_username"),
        "animestars_card_users",
        ["user_username"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_animestars_card_users_user_username"),
        table_name="animestars_card_users",
    )
    op.drop_index(
        op.f("ix_animestars_card_users_collection"),
        table_name="animestars_card_users",
    )
    op.drop_index(
        op.f("ix_animestars_card_users_card_id"),
        table_name="animestars_card_users",
    )
    op.drop_table("animestars_card_users")
    op.drop_table("animestars_cards")
    op.drop_table("animestars_users")
    CARD_STATE_ENUM.drop(op.get_bind(), checkfirst=False)
    COLLECTION_ENUM.drop(op.get_bind(), checkfirst=False)
    RANK_ENUM.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
