"""empty message

Revision ID: 66d4651d7f92
Revises: 589915f041c5
Create Date: 2025-06-22 14:07:21.932656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "66d4651d7f92"
down_revision: Union[str, None] = "589915f041c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CARD_STATS_STATE_ENUM = sa.Enum("LOCKED", "UNLOCKED", name="card_stats_state")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE card_collection ADD VALUE 'UNLOCKED_OWNED'")
    op.drop_column("animestars_card_users_stats", "state")
    CARD_STATS_STATE_ENUM.drop(bind=op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE card_collection DROP VALUE 'UNLOCKED_OWNED'")
    op.add_column(
        "animestars_card_users_stats",
        sa.Column(
            "state",
            CARD_STATS_STATE_ENUM,
            autoincrement=False,
            nullable=False,
        ),
    )
